#ifndef REQ_ANS_HPP
#define REQ_ANS_HPP

#include <string>
#include <vector>
#include <multimap>
#include <map>

const unsigned int STATUS_CODE_CONTINUE = 101;
const unsigned int STATUS_CODE_SWITCHING_PROTOCOLS = 101;
const unsigned int STATUS_CODE_OK = 200;
const unsigned int STATUS_CODE_CREATED = 201;
const unsigned int STATUS_CODE_ACCEPTED = 202;
const unsigned int STATUS_CODE_NON_AUTHORITATIVE_INFORMATION = 203;
const unsigned int STATUS_CODE_NO_CONTENT = 204;
const unsigned int STATUS_CODE_RESET_CONTENT = 205;
const unsigned int STATUS_CODE_PARTIAL_CONTENT = 206;
const unsigned int STATUS_CODE_MULTIPLE_CHOICES = 300;
const unsigned int STATUS_CODE_MOVED_PERMANENTLY = 301;
const unsigned int STATUS_CODE_MOVED_TEMPORARILY = 302;
const unsigned int STATUS_CODE_NOT_MODIFIED = 304;
const unsigned int STATUS_CODE_USE_PROXY = 305;
const unsigned int STATUS_CODE_BAD_REQUEST = 400;
const unsigned int STATUS_CODE_UNAUTHORIZED = 401;
const unsigned int STATUS_CODE_FORBIDDEN = 403;
const unsigned int STATUS_CODE_NOT_FOUND = 404;
const unsigned int STATUS_CODE_METHOD_NOT_ALLOWED = 405;
const unsigned int STATUS_CODE_NOT_ACCEPTABLE = 406;
const unsigned int STATUS_CODE_PROXY_AUTHENTICATION_REQUIRED = 407;
const unsigned int STATUS_CODE_REQUEST_TIME_OUT = 408;
const unsigned int STATUS_CODE_CONFLICT = 409;
const unsigned int STATUS_CODE_GONE = 410;
const unsigned int STATUS_CODE_LENGTH_REQUIRED = 411;
const unsigned int STATUS_CODE_PRECONDITION_FAILED = 412;
const unsigned int STATUS_CODE_REQUEST_ENTITY_TOO_LARGE = 413;
const unsigned int STATUS_CODE_REQUEST_URI_TOO_LARGE = 414;
const unsigned int STATUS_CODE_UNSUPPORTED_MEDIA_TYPE = 415;
const unsigned int STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
const unsigned int STATUS_CODE_NOT_IMPLEMENTED = 501;
const unsigned int STATUS_CODE_BAD_GATEWAY = 502;
const unsigned int STATUS_CODE_SERVICE_UNAVAILABLE = 503;
const unsigned int STATUS_CODE_GATEWAY_TIME_OUT = 504;
const unsigned int STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED = 505;

    /////////////////////////////////////////////////////////////////////////////////////
    /// uri type holds the splitted list of the scheme / hostname / path
    ///
    /// the first member is always the scheme
    /// the second member is always the host part of the URL (or an empty string for local and relative URL)
    /// the further members is the path of the URL
typedef std::vector<std::string> uri;

    /////////////////////////////////////////////////////////////////////////////////////
    /// cookies list
class cookie_list
{
public:
    unsigned int size() const { return contents.size(); };
    bool find(const std::string & key, std::string & value) const;
    void add(const std::string & key, const std::string & value) { contents[key] = value; };
    void clear() { contents.clear(); };

private:
    std::map<std::string, std::string> contents;
};

    /////////////////////////////////////////////////////////////////////////////////////
    /// class request
    ///
    /// generated by parser class, it contains the field separated request read from the associated "connexion" object
class request
{
public:
    request() { clear(); };

    void set_method_url(const std::string & method, const uri & url);
    void add_attribute(const std::string & key, const std::string & value) { attributes[key] = value; };
    void add_body(const std::string & key) { body = key; };

    const std::string & get_method() const { return meth; };
    const uri & get_uri() const { return coordinates; };
    bool find_attribute(const std::string & key, std::string & value) const;
    const std::string & get_body() const { return body; };
    cookie_list extract_cookies() const;
    void clear() { meth = ""; coordinates.clear(); attributes.clear(); body = ""; };

private:
    std::string meth;
    uri coordinates;
    std::multimap<std::string, std::string> attributes;
    std::string body;
};


    /////////////////////////////////////////////////////////////////////////////////////
    /// class answer
    ///
    /// generated by "responder" objects to provide the answer to send back to the HTTP client
class answer
{
public:
    answer() { clear(); };

    void set_status_reason(unsigned int status_code, const std::string & reason_phrase);

	/// adds or remplace a given attribute if the HTTP answer
    void add_attribute(const std::string & key, const std::string & value) { attributes[key] = value; };

	/// adds the  body to the answer
    void add_body(const std::string & key) { body = key; };

	/// retrieve the value of an attribute of the HTTP answer
	///
	/// \param[in] key is the key's attribute to look for
	/// \param[out] value is the associated value of the attribute if such attribute exists
	/// \return true if the requested attribute has been found in this request
    bool find_attribute(const std::string & key, std::string & value) const;

	/// reset the read_next_attribute to the beginning of the list
    void reset_read_next_attribute() const;

	/// reads the next attributes
	///
	/// \param[out] key key of the next attribute
	/// \param[out] value value of that attribute
	/// \return true if a next attribute has been else, key and value are not set
    bool read_next_attribute(std::string & key, std::string & value) const;


	/// add cookie to the answer
    void add_cookie(const std::string & key, std::string & value);

	/// clear all information from the object
    void clear() { status = 0; reason = ""; attributes.clear(); body = ""; next_read = attributes.begin(); };

private:
    unsigned int status;
    std::string reason;
    std::multimap<std::string, std::string> attributes;
    std::string body;
    std::multimap<std::string, std::string>::const_iterator next_read;

};

    /////////////////////////////////////////////////////////////////////////////////////
    /// pure virtual class, base class for all classes that can generate an anwser to a request

class responder
{
public:
    virtual ~responder();

    virtual answer give_answer(const request & req) = 0;
};


#endif
