#ifndef REQUEST_HPP
#define REQUEST_HPP

    // C++ system header files
#include <string>
#include <map>

    // webdar headers
#include "uri.hpp"
#include "webdar_tools.hpp"
#include "exceptions.hpp"
#include "tokens.hpp"
#include "central_report.hpp"
#include "connexion.hpp"

    /////////////////////////////////////////////////////////////////////////////////////
    /// cookies list
class cookie_list
{
public:
    unsigned int size() const { return contents.size(); };
    bool find(const std::string & key, std::string & value) const;
    void add(const std::string & key, const std::string & value) { contents[key] = value; };
    void clear() { contents.clear(); };

private:
    std::map<std::string, std::string> contents;
};

    /////////////////////////////////////////////////////////////////////////////////////
    /// class request
    ///
    /// generated by parser class, it contains the field separated request read from the associated "connexion" object




class request
{
public:
	/// The constructor
    request(central_report *log) { clear(); clog = log; };

	/// try reading just enough data in order to determine the uri of the next request
	///
	/// \note this method only fills the method and URI fields if data is available for that,
	/// in which case only, true is returned. get_method() and get_uri() can then be invoked
	/// to obtain the fields value.
    bool try_reading(connexion & input);

	/// read the next request from input connexion
	///
	/// \note this method fills the internal fields (request line, header and body)
	/// \note may throw exceptions of type exception_range and exception_input.
	/// the first mean that the request could not be read completely, the caller
	/// must either not catch this type of exception, or reply by a bad-request answer
    	/// and close the connexion even in HTTP/1.1 because be could not completely read the request.
	/// Upon exception_input, the request could be read entirely, connexion can be maintained.
	/// The request code is to send in the answer is provided by this exception class.
    void read(connexion & input);

	/// clear all fields of the request
    void clear() { status = init; cached_method = cached_uri = ""; coordinates.clear(); attributes.clear(); body = ""; };

	/// obtains the method of the read request
    const std::string & get_method() const { if(status < method_read) throw WEBDAR_BUG; return cached_method; };

	/// obtains the URI of the read request
    const uri & get_uri() const { if(status < uri_read) throw WEBDAR_BUG; return coordinates; };

	/// obtains the MAJOR version string of the read request
    int get_maj_version() const { if(status != completed) throw WEBDAR_BUG; return maj_vers; };

	/// obtains the MINOR version string of the read request
    int get_min_version() const { if(status != completed) throw WEBDAR_BUG; return min_vers; };

	/// obtain the body of the read request
    const std::string & get_body() const { if(status != completed) throw WEBDAR_BUG; return body; };

	// cookie management
    cookie_list extract_cookies() const;

	// raw request header header access
    bool find_attribute(const std::string & key, std::string & value) const;

private:
    enum { init, method_read, uri_read, reading_all, completed } status;
    std::string cached_method;    //< method already read from the next request
    std::string cached_uri;       //< uri already read from the next request
    uri coordinates;              //< uri spit in fields
    unsigned int maj_vers;        //< HTTP major version of the last request received
    unsigned int min_vers;        //< HTTP minor version of the last request received
    std::multimap<std::string, std::string> attributes; //< request header
    std::string body;             //< request body if any
    central_report *clog;         //< central report logging

	/// try reading the method and uri from the connexion
    bool read_method_uri(connexion & input, bool blocking);

	/// split the string argument in two intergers to fields maj_vers and min_vers
    void set_version(const std::string & version);

    void add_attribute(const std::string & key, const std::string & value) { attributes.insert(std::pair<std::string, std::string>(webdar_tools_to_lowercase(key), value)); };

	/// true if next to read is end of line chars (CR LF)
    static bool is_empty_line(connexion & input);

	/// returns what remains on the current lines
    static std::string up_to_eol(connexion & input);

	/// returns what remains up to no data available on the socket
    static std::string up_to_eof(connexion & input);

	/// skips the current line up to the next given argument.
	///
	/// \note Stops at end of line if the provided char is not found
    static void skip_over(connexion & input, char a);

    static std::string up_to_length(connexion & input, unsigned int length);

	/// drops all data up to and including the next end of line (CR LF).
    static void skip_line(connexion & input);

	/// returns what remains on lines up to a real EOL (not LWS)

	/// \note LWS is a CR+LF followed by any number of space or tab.
	/// LWS allow a argument to be split over several lines. The spaces and tabs
	/// following a CR+LF are not part of the argument.
	/// this structure is used in header HTTP messages (RFC 1945)
    static std::string up_to_eol_with_LWS(connexion & input);

	/// reads the next token from the socket
	/// \param[in] initial defines whether we can skip space to reach the token start
	/// \param[in] blocking defines whether the reading is blocking or not
	/// \param[out] token stores the token read
	/// \return true if a complete token could be read on the current line, false
	/// (in non blocking mode) if there is not enough data to define whether to token is
	/// complete or not.
	/// \note a token what defines the RFC 1945 at paragraph 2.2 "Basic Rules"
	/// \note the reading of a token does fails if no more token are available on the current
	/// line (CR, LF or CRLF met), true is returned in that case and token is set to an
	/// empty string
    static bool get_token(connexion & input, bool initial, bool blocking, std::string & token);


	/// read the next word from the socket

	/// \param[in] initial defines whether we can skip space to reach the word start
	/// \param[in] blocking defines whether the reading is blocking or not
	/// \param[out] word stores the read word
	/// \return true if a complete word could be read on the current line, false
	/// (in non blocking mode) if there is not enough data to define wheter the word is
	/// complete or not.
	/// \note a word is composed of token and the following characters '/' ':' '=' '@' '?'
	/// \note the reading of a word fails if end of line is met, in that case true is returned
	/// and word is set to an empty string
    static bool get_word(connexion & input, bool initial, bool blocking, std::string & word);

};

#endif
