#ifndef USER_INTERFACE_HPP
#define USER_INTERFACE_HPP

    // C system header files
extern "C"
{

}

    // C++ system header files


    // webdar headers
#include "responder.hpp"
#include "saisie.hpp"
#include "html_statistics.hpp"
#include "events.hpp"
#include "html_libdar_running.hpp"
#include "html_error.hpp"

class user_interface : public responder, public events, public actor
{
public:
	/// available event for that class
    static const std::string closing;      //< signal end of user session
    static const std::string ask_end_libdar; //< ask for a running libdar thread to end gracefully (waiting for thread to finish properly)
    static const std::string force_end_libdar; //< ask for a running libdar thread to end immediately (waiting for thread to finish properly)
    static const std::string kill_libdar_thread; //< ask to kill the libdar thread
    static const std::string clean_ended_libdar; // < ask for re-throwing possible exceptions generated by the libdar thread
    static const std::string start_restore; //< used to request a libdar thread to start
    static const std::string start_compare; //< used to request a libdar thread to start
    static const std::string start_test;    //< used to request a libdar thread to start
    static const std::string start_create;  //< used to request a libdar thread to start
    static const std::string start_isolate; //< used to request a libdar thread to start
    static const std::string start_merge;   //< used to request a libdar thread to start

    user_interface();

	/// inherited from responder
    virtual answer give_answer(const request & req);

	/// inherited from actor
    virtual void on_event(const std::string & event_name);

	/// available parameters for libdar execution
    const saisie & get_parametrage() const { return parametrage; };

	/// provides the libdar::user_interaction for libdar execution
    web_user_interaction & get_user_interaction() { return in_action.get_user_interaction(); };

	/// provides the a libdar::statistics datastructure for progressive report in libdar execution
    html_statistics & get_statistics() { return in_action.get_statistics(); };

	/// to be informed when a running thread has ended
    void libdar_has_finished();

protected:

	/// inherited from responder
    virtual void prefix_has_changed();

private:
    enum mode_type
    {
	config,        //< should display parameter selection
	listing,       //< should display listing navigation window
	running,       //< should display web_user_interface, progressive_report and cancellation button
	error,         //< should display the error
    };
    mode_type mode;        //< current mode
    mode_type return_mode; //< mode in which to return from error status
    bool close_requested;  //< whether session close has been asked
    bool mode_changed;     //< whether mode has changed
    bool libdar_has_ended; //< when set to true (in running mode) the acti(clean_ended_libdar) has to be sent to throw and catch exception from libdar

    saisie parametrage;            //< page issued in mode == config
    html_libdar_running in_action; //< page issued when a libdar thread is running (mode == running)
    html_error in_error;           //< page issued when an exception has been caught (mode == error)
};

#endif
