#ifndef USER_INTERFACE_HPP
#define USER_INTERFACE_HPP

    // C system header files
extern "C"
{

}

    // C++ system header files


    // webdar headers
#include "responder.hpp"
#include "saisie.hpp"
#include "html_statistics.hpp"
#include "web_user_interaction.hpp"
#include "events.hpp"

class user_interface : public responder, public events, public actor
{
public:
	/// available event for that class
    static const std::string closing;      //< signal end of user session
    static const std::string ask_end_libdar; //< ask for a running libdar thread to end, gently (waiting for thread to finish properly)
    static const std::string force_end_libdar; //< ask for a running libdar thread to end, forced
    static const std::string clean_ended_libdar; // < ask for re-throwing possible exceptions generated by the libdar thread
    static const std::string close_libdar_screen; //< swap back to parameter selection
    static const std::string start_restore; //< used to request a libdar thread to start
    static const std::string start_compare; //< used to request a libdar thread to start
    static const std::string start_test;    //< used to request a libdar thread to start
    static const std::string start_create;  //< used to request a libdar thread to start
    static const std::string start_isolate; //< used to request a libdar thread to start
    static const std::string start_merge;   //< used to request a libdar thread to start

    user_interface();

	/// inherited from responder
    virtual answer give_answer(const request & req);

	/// inherited from actor
    virtual void on_event(const std::string & event_name);

	/// available parameters for libdar execution
    const saisie & get_parametrage() const { return parametrage; };

	/// obtain the user_interaction for libdar
    web_user_interaction & get_user_interaction() { return web_ui; };

	/// optain the a libdar::statistics datastructure for progressive report
    html_statistics & get_statistics() { return stats; };

	/// to be informed when a running thread has ended
    void libdar_has_finished();

protected:

	/// inherited from responder
    virtual void prefix_has_changed();

private:
    enum
    {
	config,        //< should display parameter selection
	listing,       //< should display listing navigation window
	running,       //< should display web_user_interface, progressive_report and cancellation button
	end_asked,     //< should display web_user_interface, progressive_report and forced cancellation button
	end_forced,    //< should display web_user_interface, progressive_report (no button)
	exceptions,    //< should trigger libdar possible exceptions and update errors field
	finished       //< should display web_user_interface, progressive_report, eventually errors field and close button
    } mode;
    bool close_requested;
    bool mode_changed;

    saisie parametrage;
    web_user_interaction web_ui;
    html_statistics stats;
    html_button ask_close;
    html_button force_close;
    html_button finish;
    html_text errors;
    html_div run_div;
};

#endif
