/*********************************************************************/
// webdar - a web server and interface program to libdar
// Copyright (C) 2013-2024 Denis Corbin
//
// This file is part of Webdar
//
//  Webdar is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Webdar is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with Webdar.  If not, see <http://www.gnu.org/licenses/>
//
//----
//  to contact the author: dar.linux@free.fr
/*********************************************************************/

#ifndef BIBLI_RENVOI_HPP
#define BIBLI_RENVOI_HPP

    // C system header files
#include "my_config.h"
extern "C"
{

}

    // C++ system header files

    // webdar headers
#include "reference.hpp"
#include "bibli_referable.hpp"

    /// \file bibli_renvoi.hpp defines bibli_renvoi class


    /// class bibli_renvoi

    /// objects of that class are generated by a bibliotheque object
    /// and given a category and name setup a reference to that object
    /// stored in the bibliotheque. They become a place-holder for that
    /// bibliotheque managed object in some other objects of the same
    /// bibliotheque

class bibli_renvoi: protected reference
{
public:
    bibli_renvoi(bibli_referable* ptr);
    bibli_renvoi(const bibli_renvoi & ref) = default;
    bibli_renvoi(bibli_renvoi && ref) noexcept(false) = default;
    bibli_renvoi & operator = (const bibli_renvoi & ref) = default;
    bibli_renvoi & operator = (bibli_renvoi && ref) noexcept(false) = default;
    virtual ~bibli_renvoi() {};

    const bibli_referable* get_reference() const;

};

#endif
